### ISSUE TITLE
privateKey option can't be set in the "options" object

### ISSUE THREAD

**Issue by AoDev** [oncletom/grunt-crx#45]
Hello, 

This works:

```
    crx: {
      example: {
        options: {
          baseURL: 'http://...'
        },
        privateKey: 'key/chrome.pem',
        src: dir,
        dest: dir,
        filename: 'example.crx'
      }
    },
```

This does not work: (and your docs are like this)
```
    crx: {
      example: {
        options: {
          baseURL: 'http://...',
          privateKey: 'key/chrome.pem',
        },
        src: dir,
        dest: dir,
        filename: 'example.crx'
      }
    },
```

**Comment by mbernath** [comment]
Hi, I can also confirm the bug using 0.3.4.

**Comment by jpalomar** [comment]
i think this bug is resolved in the pull request: https://github.com/oncletom/grunt-crx/pull/47

**Comment by oncletom** [comment]
Hello guys!

- in 0.3.x: you have to use `grunt.target.privateKey`;
- in 1.x: you have yo use `grunt.target.options.privateKey`

The last one did not work but #47 fixed it :-) The v1 branch is not yet the `latest` one in term of npm because of a critical bug (files are not excluded and it can be a severe security breach).

```bash
npm install --save grunt-crx // installs grunt-crx@0.3.x
npm install --save grunt-crx@beta // installs grunt-crx@1.x
```
