### ISSUE TITLE
zipDest does not include all files

### ISSUE THREAD

**Issue by richburdon** [oncletom/grunt-crx#60]
I have a src attribute that specifies multiple directories (below). I have confirmed that these files are properly expanded (e.g., 3 files from both = 6 files), but the zip file only contains files from the directory that contains the manifest file.

    crx: {
      demo: {
        options: {
          privateKey: 'sub/config/keys/crx-demo.pem'
        },
        src: [
          'src/main/javascript/crx/demo/**/*',
          'src/main/resources/crx/demo/**/*'
        ],
        zipDest: 'target/crx/demo.zip',
        dest: 'target/crx/demo.crx'
      }
    }

**Comment by fcfort** [comment]
HI @richburdon, I am having the same issue.

This is happening because of a bug in crx.js, specifically, this one:

https://github.com/oncletom/grunt-crx/blob/master/lib/crx.js#L105

Basically what is happening is that the line includes all files (including directories) like so:

 'app/dist/icon.js',
  'app/dist/libs.js',
  'app/dist/main.js',
  'app/images',
  'app/images/icon128.png',
  'app/images/icon38.png',
  'app/libs',
  'app/libs/mutation-summary.js',
  'app/libs/patch-worker.js',
  'app/libs/pdf.js',
  'app/libs/pdf.worker.js',
  'app/manifest.json',
  'app/src',

Then the exclusion logic on line https://github.com/oncletom/grunt-crx/blob/master/lib/crx.js#L59 does an rm -rf on those dirs, thus removing them the zip file.

To resolve this, the logic above needs to do a test to only remove files (and not directories).

I'll have a pr out for it in a hot minute.

In the meantime, you can change the line:

`grunt.file.expand(sourceDir + '/**/*')`

to

`
grunt.file.expand(sourceDir + '/**/*').filter(function(file) {
      return grunt.file.isFile(file);
    })
`

And it should work for you.

**Comment by fcfort** [comment]
pr created https://github.com/oncletom/grunt-crx/pull/68
